spring:
  cloud:
    config:
      # 指定configserver的地址
      uri: http://configserver.com:9999
      # 指定要访问的远程库的分支
      label: master
      # 指定要从远程库中读取的文件名，无需扩展名
      name: application-mybatis-config
      # 指定要选择的环境
  application:
    name: jdbc-demo
#      profile: dev
server:
  port: 8566

eureka:
  instance:
    prefer-ip-address: true  #注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
