








#person:
#  lastName: hello
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 12
#激活devc环境
spring:
  profiles:
    active: devc
---
server:
  port: 8084
spring:
  profiles: prodc
---
server:
     port: 8085
spring:
  profiles: devc