server:
  port: 9999
# 指定当前工程所关联的git远程库地址
spring:
  application:
    name: student-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChenFang341200/configServer.git
          username: ChenFang341200
          password: cc341200


eureka:
  instance:
    prefer-ip-address: true  #注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS