server:
  port: 9999
# 指定当前工程所关联的git远程库地址
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChenFang341200/configServer.git
          username: ChenFang341200
          password: cc341200

eureka:
  client:
    # 指定Eureka服务注册中心
    service-url:
      defaultZone: http://localhost:8000/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS